In [4]:
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append('../../src')
from scrape_transform_save import *

In [ ]:
# MOVER XLS DE DESCARGAS A RAW DATA:

origen = 'C:/Users/CIara/Downloads'

raw = '../../data/raw/'

move_excel(origen, raw)

In [3]:
# TRANFORMAR RAW DATA Y PASARLO A PROCESSED:

from src.scrape_transform_save import process_excel_files


processed = '../../data/processed'
raw = '../../data/raw'

process_excel_files(raw,processed)

In [5]:
df = pd.read_csv('../../data/processed/Indice_de_calidad_de_vida_infantil_relacionada_con_la_salud.csv')

df

    id                        Region   Año Hombre  Mujer  Total
0    1                   España (ES)  2017  87.22  87.58  87.40
1    2                Andalucía (AN)  2017  89.75  90.18  89.96
2    3                   Aragón (AR)  2017  91.38  93.29  92.31
3    4  Asturias, Principado de (AS)  2017  79.26  82.13  80.74
4    5           Balears, Illes (IB)  2017  92.88   91.2  92.06
5    6                 Canarias (CN)  2017  92.77  91.96  92.39
6    7                Cantabria (CB)  2017  91.42  94.68  93.04
7    8          Castilla y León (CL)  2017  87.13  86.48  86.81
8    9     Castilla - La Mancha (CM)  2017  85.57  84.98  85.28
9   10                 Cataluña (CT)  2017  85.09  85.99  85.52
10  11     Comunitat Valenciana (VC)  2017   84.8  83.76  84.29
11  12              Extremadura (EX)  2017  89.56  89.63  89.60
12  13                  Galicia (GA)  2017  82.68  83.88  83.29
13  14     Madrid, Comunidad de (MD)  2017  87.67  88.39  88.02
14  15        Murcia, Región de (MC)  2017  87.27  86.93  87.11
15  16     Navarra, C. Foral de (NC)  2017   86.9  90.06  88.36
16  17               País Vasco (PV)  2017  85.85  87.56  86.71
17  18                 La Rioja (RI)  2017  89.71  84.23  86.93
18  19                    Ceuta (CE)  2017     --     --  84.37
19  20                  Melilla (ML)  2017     --     --  82.28